baseURL = "https://lasasurveyor.org/"
languageCode = "en-us"
title = "LASA Surveyor"

[params]
isSurveyUnlocked = false
surveyURL = "https://forms.gle/28xqVam4Lb83yEzLA"

[menus]
[[menus.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menus.main]]
name = "About/Contact"
pageRef = "/about/"
weight = 4

[[menus.main]]
name = "Posts"
pageRef = "/posts/"
weight = 3

[[menus.main]]
name = "Survey"
pageRef = "/survey/"
weight = 2
